POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "higo",
    "name": "Masahigo",
    "password": "supersalainen"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "testblogger",
    "name": "Test Blogger",
    "password": "secretpwd"
}