POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Tech blog about public clouds and devops using MS stack.",
    "author": "Masi Malmi",
    "url": "https://msdevopsdude.com",
    "likes": 100,
    "userId": "5fcce4c0e5d35a1cb9f7ae85"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The best posts about DevOps",
    "author": "Polar Squad",
    "url": "https://polarsquad.com/blog",
    "likes": 1000,
    "userId": "5fcce4c0e5d35a1cb9f7ae85"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "False blog",
    "author": "John Doe",
    "url": "http://falseblogs.com",
    "userId": "12345"
}